import pygame
import colores

ALTO_VENTANA = 600
ANCHO_VENTANA = 720
FPS = 60
DEBUG=False
#TEXTO
TAM_SCORE = 15
#IMAGENES
PATH_IMG = "img/"
PATH_MSC = "music/"
#CANT ENEMIGOS
ENEMIGOS_COL_LVL1=1
ENEMIGOS_COL_LVL2=1
ENEMIGOS_COL_LVL3=1
ENEMIGOS_COL_LVL4=1
ENEMIGOS_COL_LVL5=1
ENEMIGOS_FILA_LVL1=1
ENEMIGOS_FILA_LVL2=1
ENEMIGOS_FILA_LVL3=1

#ENEMIGOS
BASE_ENEMIGA = 10
TAMANIO_NAVE_ENEMIGA = 60
TAMANIO_BOSS_ENEMIGA = 200
DESPLAZAMIENTO = 5
DIFICULTAD = 10000
NAVE_ENEMIGA_1 = "spiked1.png"
NAVE_ENEMIGA_2 = "spiked2.png"
NAVE_ENEMIGA_3 = "spiked3.png"
NAVE_BOSS_1 = "shipboss1.png"
NAVE_BOSS_2 = "shipboss2.png"
NAVE_BOSS_3 = "final.png"
#PLAYER
VELOCIDAD_NAVE_PPAL=5
VIDAS = 3
TAM_VIDAS = (30,20)
imagen_player = pygame.image.load(PATH_IMG+"player_ship.png")
TAM = (int(imagen_player.get_width()/4),imagen_player.get_height())